### ISSUE TITLE
Front-end logs out unexpectedly -> 401 unauthorized

### ISSUE THREAD

**Issue by gbmarc1** [HumanSignal/label-studio-frontend#1607]
**Describe the bug**
The front-end very often receive a 401 unauthorized error and brings the user back to the login page. If the user, press back the app is still logged in and can continue his work.

We noticed that this would happen very frequently when memory was low. We scaled up the resources and now it happens less frequently but still quite often.

**To Reproduce**
Play around in the UI and at one point the UI will go back to the login page.

**Screenshots**
```
 Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/sentry_sdk/integrations/django/__init__.py", line 304, in sentry_patched_drf_initial
    return old_drf_initial(self, request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 415, in initial
    self.check_permissions(request)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 333, in check_permissions
    self.permission_denied(
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 174, in permission_denied
    raise exceptions.NotAuthenticated()
rest_framework.exceptions.NotAuthenticated: Authentication credentials were not provided. 
```
![image](https://github.com/HumanSignal/label-studio-frontend/assets/29891099/d601583d-5016-4acf-a8d7-b8b4cce8a0ad)

**Environment (please complete the following information):**
 - OS: ubuntu
 - Label Studio Version 1.9.1.post0

**Additional context**
We use GCP cloudrun and use a gs:// storage.

It seems the session_id has changed between the last successful api call ( for example `/projects/5`). It seems it took the session_id of the `/presign` request.

It seems it occurs often after `429 Too Many Requests` with the `ingest.sentry.io/api/.../store/?sentry_key=...` request.
![image](https://github.com/HumanSignal/label-studio-frontend/assets/29891099/08ab28fb-c083-499e-b991-7982f6e4cba1)

**Comment by gbmarc1** [comment]
Could this be related to this [issue](https://github.com/HumanSignal/label-studio/issues/3349)?

**Comment by gbmarc1** [comment]
The problem was that I was not setting the SECRET_KEY env variable. So, when my services were scaling up, the new pods did not decode the cookie properly prompting re-authentication.

**Comment by jombooth** [comment]
Glad you were able to get it fixed + appreciate you following up here so that others can benefit from your findings. Cheers! :beer:

**Comment by EgShes** [comment]
@gbmarc1 Could you please tell what env you set exactly to fix this?

**Comment by EgShes** [comment]
I managed to find out. Yes, you just set `SECRET_KEY` as is.

Here is the [line](https://github.com/HumanSignal/label-studio/blob/b08b6237b40ea0a568229b116d5b6db7d5c1643a/label_studio/core/settings/label_studio.py#L9) in code, where this env is read.
